version: "3.7"

services:
    db:
        image: mysql:8.0.33
        container_name: laravel-db
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./docker/dbdata:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - ${DB_PORT}:3306
        networks:
            - laravel-network
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: laravel-docker
        container_name: laravel-app
        links:
            - db
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel-network
    nginx:
        image: nginx:alpine
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/php-fpm.conf:/etc/nginx/php-fpm.conf
            - ./docker/nginx/server-ssl.conf:/etc/nginx/server.conf
            - ./docker/nginx/ssl:/etc/nginx/ssl
            - ./docker/nginx/log:/var/nginx/log
        ports:
            - "80:80"
            - "443:443"
        links:
            - app
        networks:
            - laravel-network

volumes:
  dbdata:
    driver: local

networks:
    laravel-network:
